#index:
#    path: /
#    controller: App\Controller\DefaultController::index

task_home:
    path: /
    controller: App\Controller\TaskController::home

task_list:
    path: tasks/list
    controller: App\Controller\TaskController::index
    host: projeto.test

task_show:
    path: tasks/show/{id?}
    controller: App\Controller\TaskController::show

task_create:
    path: tasks/create
    controller: App\Controller\TaskController::create
    methods: [GET,POST]

task_edit:
    path: tasks/{id}/edit
    controller: App\Controller\TaskController::edit
    methods: [GET,POST]

task_delete:
    path: tasks/{id}
    controller: App\Controller\TaskController::delete
   # methods: [DELETE]
